BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: textInput
        BoxLayout:
            size_hint_x: 0.2
            orientation: 'vertical'
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert m to km'
    Label:
        text: "Numbers here"
        color: (1,1,0,1)
        font_size: 25





